 PTSTAT
 'AT TIME T = ',(⍕T3←T3+T),' SEC. STATS ARE AS FOLLOWS:'
 '          VERTICAL           TRANSVERSE        HORIZONTAL'
 'DISTANCE',9↓(18 2⍕D),' METERS'
 'VELOCITY',9↓(18 2⍕V),'MTRS/SEC.'
 'FUEL... ',(2⍕F),' BURN UNITS'
 'COMPUTED TIME TO IMPACT AT PRESENT RATE... ',(2⍕TF×D[0]>0.001),' SECONDS.'
